project_id: ""
api_token: ""
preserve_hierarchy: true
files: [
    # JSON 翻译文件
    { source: "/i18n/en/**/*", translation: "/i18n/%two_letters_code%/**/%original_file_name%" },
    # 文档 Markdown 文件
    {
      source: "/docs/**/*",
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%",
    },
  ]
