name: ci-prod

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          always-auth: false
          node-version: 14.x

      - name: Checkout code repo
        uses: actions/checkout@v2

      - name: Check cache for yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-prod-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn
        run: yarn install

      - name: Build
        run: |
          yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: build/*
          retention-days: 1

  deploy-to-server:
    name: deploy the hotpot docs frontend to static server
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: doc

      - name: Deploy index to server
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FLUX_STATIC_SERVER_PK }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: '.'
          REMOTE_HOST: ${{ secrets.FLUX_STATIC_SERVER_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/usr/local/www/hotpot-docs/'

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: doc
